---
title: "Midterm_draft"
author: ""
date: "3/2/2021"
output: html_document
---

```{r}
drugs <- read.csv(file="salesweekly.csv", header=TRUE)

drugs$datum <- as.Date(drugs$datum, "%m/%d/%Y")
anhist <- drugs$R06
head(drugs)

#Citation: Chapter 05 notes, https://www.earthdatascience.org/courses/earth-analytics/time-series-data/date-class-in-r/

plot(anhist~drugs$datum, type='l')

```

Let's take a look at this data in the frequency domain:
```{r}
anhist_spec <- spectrum(anhist)
plot(anhist_spec$freq*52, anhist_spec$spec, type='l', log='y')
```

We'll try to separate out the low frequency trend and high frequency noise to extract the cyclical behavior via a loess bandpass filter:

```{r}
anhist_low <- ts(loess(anhist~as.numeric(drugs$datum), span=0.5)$fitted, start=2014, frequency=52)
anhist_high <- ts(anhist - loess(anhist~as.numeric(drugs$datum), span=0.1)$fitted, start=2014, frequency=52)

anhist_cycles <- anhist - anhist_high - anhist_low

plot(ts.union(anhist, anhist_low, anhist_high, anhist_cycles))

cycle_spec <- spectrum(anhist_cycles)

##Citation: From Chapter 8 notes
```

Now let's extract the peak frequency of our cyclic data, to see if our hypothesis of a year long cycle holds up:

```{r}
peak_freq <- cycle_spec$freq[which.max(cycle_spec$spec)]

peak_freq
period <- 1/peak_freq
period
```

We end with a period of approximately 1 year! Success!